using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DirectConnectionPredictControl.CommenTool
{
    public class HistoryDataModel
    {
        #region column row binding data
        public int ID { get; set; }
        public int LifeSig_1 { get; set; }
        public int LifeSig_2 { get; set; }
        public int LifeSig_3 { get; set; }
        public int LifeSig_4 { get; set; }
        public int LifeSig_5 { get; set; }
        public int LifeSig_6 { get; set; }
        public DateTime dateTime { get; set; }
        public double RefSpeed { get; set; }
        public string Mode { get; set; }
        public bool BrakeCmd { get; set; }
        public bool DriveCmd { get; set; }
        public bool FastBrakeCmd { get; set; }
        public bool LazyCmd { get; set; }
        public bool EmergencyBrakeCmd { get; set; }
        public bool HoldBrakeRealease { get; set; }
        public bool LazyState { get; set; }
        public bool DriveState { set; get; }
        public bool NormalBrakeState { get; set; }
        public bool EmergencyBrakeState { get; set; }
        public bool ZeroSpeed { get; set; }
        public int BrakeLevel { get; set; }
        public int TrainBrakeForce { get; set; }
        public double SpeedAx1_1 { get; set; }
        public double SpeedAx2_1 { get; set; }
        public double SpeedAx1_2 { get; set; }
        public double SpeedAx2_2 { get; set; }
        public double SpeedAx1_3 { get; set; }
        public double SpeedAx2_3 { get; set; }
        public double SpeedAx1_4 { get; set; }
        public double SpeedAx2_4 { get; set; }
        public double SpeedAx1_5 { get; set; }
        public double SpeedAx2_5 { get; set; }
        public double SpeedAx1_6 { get; set; }
        public double SpeedAx2_6 { get; set; }
        public bool VCM2MVBState_1 { get; set; }
        public bool VCM2MVBState_2 { get; set; }
        public bool Slip_1 { get; set; }
        public bool Slip_2 { get; set; }
        public bool Slip_3 { get; set; }
        public bool Slip_4 { get; set; }
        public bool Slip_5 { get; set; }
        public bool Slip_6 { get; set; }
        public bool EmergencyBrakeActive_1 { get; set; }
        public bool EmergencyBrakeActive_2 { get; set; }
        public bool EmergencyBrakeActive_3 { get; set; }
        public bool EmergencyBrakeActive_4 { get; set; }
        public bool EmergencyBrakeActive_5 { get; set; }
        public bool EmergencyBrakeActive_6 { get; set; }
        public bool NotZeroSpeed { get; set; }
        public bool AbActive_1 { get; set; }
        public bool AbActive_2 { get; set; }
        public bool AbActive_3 { get; set; }
        public bool AbActive_4 { get; set; }
        public bool AbActive_5 { get; set; }
        public bool AbActive_6 { get; set; }
        public bool BSRLow_1 { get; set; }
        public bool BSRLow_2 { get; set; }
        public bool BSRLow_3 { get; set; }
        public bool BSRLow_4 { get; set; }
        public bool BSRLow_5 { get; set; }
        public bool BSRLow_6 { get; set; }
        public bool ParkBreakRealease { get; set; }
        public bool AbStatues_1 { get; set; }
        public bool AbStatues_2 { get; set; }
        public bool AbStatues_3 { get; set; }
        public bool AbStatues_4 { get; set; }
        public bool AbStatues_5 { get; set; }
        public bool AbStatues_6 { get; set; }
        public bool MassValid_1 { get; set; }
        public bool MassValid_2 { get; set; }
        public bool MassValid_3 { get; set; }
        public bool MassValid_4 { get; set; }
        public bool MassValid_5 { get; set; }
        public bool MassValid_6 { get; set; }
        public int AbTargetValue_1 { get; set; }
        public int AbTargetValue_2 { get; set; }
        public int AbTargetValue_3 { get; set; }
        public int AbTargetValue_4 { get; set; }
        public int AbTargetValue_5 { get; set; }
        public int AbTargetValue_6 { get; set; }
        public bool SelfInt { get; set; }
        public bool SelfActive { get; set; }
        public bool SelfSuccess { get; set; }
        public bool SelfFail { get; set; }
        public bool UnTest24 { get; set; }
        public bool UnTest26 { get; set; }
        public bool GatewayValveState { get; set; }
        public bool HardDrive { get; set; }
        public bool HardBrake { get; set; }
        public bool HardFastBrake { get; set; }
        public bool HardEmergencyBrake { get; set; }
        public bool HardEmergencyDrive { get; set; }
        public bool CanUnitTestOn { get; set; }
        public bool CanValveActive { get; set; }
        public bool CanUnitTestOff { get; set; }
        public bool NetDrive { get; set; }
        public bool NetBrake { get; set; }
        public bool NetFastBrake { get; set; }
        public bool TowingMode { get; set; }
        public bool KeepBrakeRelease { get; set; }
        public bool CanTestA { get; set; }
        public bool CanTestB { get; set; }
        public bool BrakeLevelActive { get; set; }
        public bool SelfTestCmd { get; set; }
        public bool TrainBrakeEnable { get; set; }
        public bool AbFadeOut { get; set; }
        public bool EDoutB { get; set; }
        public bool EDoutC { get; set; }
        public bool WheelInputState { get; set; }
        public int BrakeCylinderSourcePressure_1 { get; set; }
        public int BrakeCylinderSourcePressure_2 { get; set; }
        public int BrakeCylinderSourcePressure_3 { get; set; }
        public int BrakeCylinderSourcePressure_4 { get; set; }
        public int BrakeCylinderSourcePressure_5 { get; set; }
        public int BrakeCylinderSourcePressure_6 { get; set; }
        public int AirSpringPressure1_1 { get; set; }
        public int AirSpringPressure1_2 { get; set; }
        public int AirSpringPressure1_3 { get; set; }
        public int AirSpringPressure1_4 { get; set; }
        public int AirSpringPressure1_5 { get; set; }
        public int AirSpringPressure1_6 { get; set; }
        public int AirSpringPressure2_1 { get; set; }
        public int AirSpringPressure2_2 { get; set; }
        public int AirSpringPressure2_3 { get; set; }
        public int AirSpringPressure2_4 { get; set; }
        public int AirSpringPressure2_5 { get; set; }
        public int AirSpringPressure2_6 { get; set; }
        public int ParkPressure_1 { get; set; }
        public int ParkPressure_2 { get; set; }
        public int ParkPressure_3 { get; set; }
        public int ParkPressure_4 { get; set; }
        public int VldRealPressure_1 { get; set; }
        public int VldRealPressure_2 { get; set; }
        public int VldRealPressure_3 { get; set; }
        public int VldRealPressure_4 { get; set; }
        public int VldRealPressure_5 { get; set; }
        public int VldRealPressure_6 { get; set; }
        public int Bcp1Pressure_1 { get; set; }
        public int Bcp2Pressure_1 { get; set; }
        public int Bcp1Pressure_6 { get; set; }
        public int Bcp2Pressure_6 { get; set; }
        public int Bcp1Pressure_2 { get; set; }
        public int Bcp2Pressure_2 { get; set; }
        public int Bcp1Pressure_3 { get; set; }
        public int Bcp2Pressure_3 { get; set; }
        public int Bcp1Pressure_4 { get; set; }
        public int Bcp2Pressure_4 { get; set; }
        public int Bcp1Pressure_5 { get; set; }
        public int Bcp2Pressure_5 { get; set; }
        public bool BSSRSenorFault_1 { get; set; }
        public bool BSSRSenorFault_2 { get; set; }
        public bool BSSRSenorFault_3 { get; set; }
        public bool BSSRSenorFault_4 { get; set; }
        public bool BSSRSenorFault_5 { get; set; }
        public bool BSSRSenorFault_6 { get; set; }
        public bool AirSpringSenorFault1_1 { get; set; }
        public bool AirSpringSenorFault2_1 { get; set; }
        public bool AirSpringSenorFault1_2 { get; set; }
        public bool AirSpringSenorFault2_2 { get; set; }
        public bool AirSpringSenorFault1_3 { get; set; }
        public bool AirSpringSenorFault2_3 { get; set; }
        public bool AirSpringSenorFault1_4 { get; set; }
        public bool AirSpringSenorFault2_4 { get; set; }
        public bool AirSpringSenorFault1_5 { get; set; }
        public bool AirSpringSenorFault2_5 { get; set; }
        public bool AirSpringSenorFault1_6 { get; set; }
        public bool AirSpringSenorFault2_6 { get; set; }
        public bool ParkCylinderSenorFault_1 { get; set; }
        public bool ParkCylinderSenorFault_2 { get; set; }
        public bool ParkCylinderSenorFault_3 { get; set; }
        public bool ParkCylinderSenorFault_4 { get; set; }
        public bool ParkCylinderSenorFault_5 { get; set; }
        public bool ParkCylinderSenorFault_6 { get; set; }
        public bool VLDSensorFault_1 { get; set; }
        public bool VLDSensorFault_2 { get; set; }
        public bool VLDSensorFault_3 { get; set; }
        public bool VLDSensorFault_4 { get; set; }
        public bool VLDSensorFault_5 { get; set; }
        public bool VLDSensorFault_6 { get; set; }
        public bool BSRSenorFault1_1 { get; set; }
        public bool BSRSenorFault2_1 { get; set; }
        public bool BSRSenorFault1_2 { get; set; }
        public bool BSRSenorFault2_2 { get; set; }
        public bool BSRSenorFault1_3 { get; set; }
        public bool BSRSenorFault2_3 { get; set; }
        public bool BSRSenorFault1_4 { get; set; }
        public bool BSRSenorFault2_4 { get; set; }
        public bool BSRSenorFault1_5 { get; set; }
        public bool BSRSenorFault2_5 { get; set; }
        public bool BSRSenorFault1_6 { get; set; }
        public bool BSRSenorFault2_6 { get; set; }
        public bool AirSpringOverflow1_1 { get; set; }
        public bool AirSpringOverflow2_1 { get; set; }
        public bool AirSpringOverflow1_2 { get; set; }
        public bool AirSpringOverflow2_2 { get; set; }
        public bool AirSpringOverflow1_3 { get; set; }
        public bool AirSpringOverflow2_3 { get; set; }
        public bool AirSpringOverflow1_4 { get; set; }
        public bool AirSpringOverflow2_4 { get; set; }
        public bool AirSpringOverflow1_5 { get; set; }
        public bool AirSpringOverflow2_5 { get; set; }
        public bool AirSpringOverflow1_6 { get; set; }
        public bool AirSpringOverflow2_6 { get; set; }
        public int VldPressureSetup_1 { get; set; }
        public int VldPressureSetup_2 { get; set; }
        public int VldPressureSetup_3 { get; set; }
        public int VldPressureSetup_4 { get; set; }
        public int VldPressureSetup_5 { get; set; }
        public int VldPressureSetup_6 { get; set; }
        public int Mass_1 { get; set; }
        public int Mass_2 { get; set; }
        public int Mass_3 { get; set; }
        public int Mass_4 { get; set; }
        public int Mass_5 { get; set; }
        public int Mass_6 { get; set; }
        public bool BCUFail_Serious_1 { get; set; }
        public bool BCUFail_Middle_1 { get; set; }
        public bool BCUFail_Slight_1 { get; set; }
        public bool BCUFail_Serious_2 { get; set; }
        public bool BCUFail_Middle_2 { get; set; }
        public bool BCUFail_Slight_2 { get; set; }
        public bool BCUFail_Serious_3 { get; set; }
        public bool BCUFail_Middle_3 { get; set; }
        public bool BCUFail_Slight_3 { get; set; }
        public bool BCUFail_Serious_4 { get; set; }
        public bool BCUFail_Middle_4 { get; set; }
        public bool BCUFail_Slight_4 { get; set; }
        public bool BCUFail_Serious_5 { get; set; }
        public bool BCUFail_Middle_5 { get; set; }
        public bool BCUFail_Slight_5 { get; set; }
        public bool BCUFail_Serious_6 { get; set; }
        public bool BCUFail_Middle_6 { get; set; }
        public bool BCUFail_Slight_6 { get; set; }
        public bool EmergencyBrakeFault_1 { get; set; }
        public bool EmergencyBrakeFault_2 { get; set; }
        public bool EmergencyBrakeFault_3 { get; set; }
        public bool EmergencyBrakeFault_4 { get; set; }
        public bool EmergencyBrakeFault_5 { get; set; }
        public bool EmergencyBrakeFault_6 { get; set; }
        public bool SpeedSenorFault1_1 { get; set; }
        public bool SpeedSenorFault2_1 { get; set; }
        public bool SpeedSenorFault1_2 { get; set; }
        public bool SpeedSenorFault2_2 { get; set; }
        public bool SpeedSenorFault1_3 { get; set; }
        public bool SpeedSenorFault2_3 { get; set; }
        public bool SpeedSenorFault1_4 { get; set; }
        public bool SpeedSenorFault2_4 { get; set; }
        public bool SpeedSenorFault1_5 { get; set; }
        public bool SpeedSenorFault2_5 { get; set; }
        public bool SpeedSenorFault1_6 { get; set; }
        public bool SpeedSenorFault2_6 { get; set; }
        public bool WSPFault1_1 { get; set; }
        public bool WSPFault2_1 { get; set; }
        public bool WSPFault1_2 { get; set; }
        public bool WSPFault2_2 { get; set; }
        public bool WSPFault1_3 { get; set; }
        public bool WSPFault2_3 { get; set; }
        public bool WSPFault1_4 { get; set; }
        public bool WSPFault2_4 { get; set; }
        public bool WSPFault1_5 { get; set; }
        public bool WSPFault2_5 { get; set; }
        public bool WSPFault1_6 { get; set; }
        public bool WSPFault2_6 { get; set; }
        public bool CodeConnectorFault_1 { get; set; }
        public bool CodeConnectorFault_2 { get; set; }
        public bool CodeConnectorFault_3 { get; set; }
        public bool CodeConnectorFault_4 { get; set; }
        public bool CodeConnectorFault_5 { get; set; }
        public bool CodeConnectorFault_6 { get; set; }
        public bool AirSpringLimit_1 { get; set; }
        public bool AirSpringLimit_2 { get; set; }
        public bool AirSpringLimit_3 { get; set; }
        public bool AirSpringLimit_4 { get; set; }
        public bool AirSpringLimit_5 { get; set; }
        public bool AirSpringLimit_6 { get; set; }
        public bool BrakeNotRealease_1 { get; set; }
        public bool BrakeNotRealease_2 { get; set; }
        public bool BrakeNotRealease_3 { get; set; }
        public bool BrakeNotRealease_4 { get; set; }
        public bool BrakeNotRealease_5 { get; set; }
        public bool BrakeNotRealease_6 { get; set; }
        public bool BCPLow_1 { get; set; }
        public bool BCPLow_2 { get; set; }
        public bool BCPLow_3 { get; set; }
        public bool BCPLow_4 { get; set; }
        public bool BCPLow_5 { get; set; }
        public bool BCPLow_6 { get; set; }
        public int VCMLifeSig { get; set; }
        public int DCULifeSig_1 { get; set; }
        public int DCULifeSig_2 { get; set; }
        public int DCULifeSig_3 { get; set; }
        public int DCULifeSig_4 { get; set; }
        public bool DCU_Ed_Ok_1 { get; set; }
        public bool DCU_Ed_Fadeout_1 { get; set; }
        public bool DCU_Ed_Slip_1 { get; set; }
        public bool DCU_Ed_Ok_2 { get; set; }
        public bool DCU_Ed_Fadeout_2 { get; set; }
        public bool DCU_Ed_Slip_2 { get; set; }
        public bool DCU_Ed_Ok_3 { get; set; }
        public bool DCU_Ed_Fadeout_3 { get; set; }
        public bool DCU_Ed_Slip_3 { get; set; }
        public bool DCU_Ed_Ok_4 { get; set; }
        public bool DCU_Ed_Fadeout_4 { get; set; }
        public bool DCU_Ed_Slip_4 { get; set; }
        public int DcuEbRealValue_1 { get; set; }
        public int DcuEbRealValue_2 { get; set; }
        public int DcuEbRealValue_3 { get; set; }
        public int DcuEbRealValue_4 { get; set; }
        public int DcuMax_1 { get; set; }
        public int DcuMax_2 { get; set; }
        public int DcuMax_3 { get; set; }
        public int DcuMax_4 { get; set; }
        public int AbCapacity_1 { get; set; }
        public int AbCapacity_2 { get; set; }
        public int AbCapacity_3 { get; set; }
        public int AbCapacity_4 { get; set; }
        public int AbCapacity_5 { get; set; }
        public int AbCapacity_6 { get; set; }
        public int AbRealValue_1 { get; set; }
        public int AbRealValue_2 { get; set; }
        public int AbRealValue_3 { get; set; }
        public int AbRealValue_4 { get; set; }
        public int AbRealValue_5 { get; set; }
        public int AbRealValue_6 { get; set; }
        public bool SpeedDetection { get; set; }
        public bool CanBusFail1 { get; set; }
        public bool CanBusFail2 { get; set; }
        public bool HardDifferent { get; set; }
        public bool Event_High { get; set; }
        public bool Event_Middle { get; set; }
        public bool Event_Low { get; set; }
        public bool CanASPActive { get; set; }
        public bool BCPLowA { get; set; }
        public bool BCPLowB { get; set; }
        public bool BCPLowC { get; set; }
        public int SoftVersion { get; set; }

        #endregion
    }
}
